import assert from "node:assert/strict";
import test from "node:test";
import { ADMINISTRATIVE_RECONCILIATION_QUERY, handleAdministrativeBillingReconciliation } from "./administrative-billing-reconciliation.server";

const target = { subscriptionContractId: "gid://shopify/SubscriptionContract/10", subscriptionBillingAttemptId: "gid://shopify/SubscriptionBillingAttempt/20", shopifyOrderId: "gid://shopify/Order/30", cycleOriginTime: "2026-09-27T16:00:00Z", correlationId: "scope9-live-cycle", dryRun: true };
function request(body: any = target, url = "https://app.test/app/billing-reconciliation") { return new Request(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); }
function setup(overrides: Record<string, any> = {}) {
  let graphqlCalls = 0; const centralBodies: any[] = [], logs: any[] = [];
  const data = { shop: { id: "gid://shopify/Shop/1" }, subscriptionBillingAttempt: { id: target.subscriptionBillingAttemptId, originTime: target.cycleOriginTime, createdAt: "2026-08-28T12:00:00Z", completedAt: "2026-08-28T12:00:01Z", subscriptionContract: { id: target.subscriptionContractId }, state: { __typename: "SubscriptionBillingAttemptSuccessState", order: { id: target.shopifyOrderId, test: true, displayFinancialStatus: "PAID", processedAt: "2026-08-28T12:00:01Z", currentTotalPriceSet: { shopMoney: { amount: "50.19", currencyCode: "BRL" } }, transactions: [{ gateway: "bogus", test: true, status: "SUCCESS" }] } } } };
  const dependencies: any = { authenticate: async () => ({ session: { shop: "one.myshopify.com", accessToken: "never-forward" }, admin: { graphql: async () => { graphqlCalls++; return Response.json({ data }); } } }), apiUrl: "https://central.test", apiKey: "central-secret", fetchFn: async (_url: any, init: any) => { centralBodies.push(JSON.parse(init.body)); return Response.json({ status: "dry_run" }); }, logger: { error: (...args: any[]) => logs.push(args) }, ...overrides };
  return { dependencies, data, centralBodies, logs, get graphqlCalls() { return graphqlCalls; } };
}

test("invalid Shopify session performs no GraphQL or Central API call", async () => { const s = setup({ authenticate: async () => { throw new Response("unauthorized", { status: 401 }); } }); const response = await handleAdministrativeBillingReconciliation(request(), s.dependencies); assert.equal(response.status, 401); assert.equal(s.graphqlCalls, 0); assert.equal(s.centralBodies.length, 0); });
test("authenticated action gets shop domain from session and shopId from GraphQL", async () => { const s = setup(); const response = await handleAdministrativeBillingReconciliation(request(), s.dependencies); assert.equal(response.status, 200); assert.equal(s.centralBodies[0].shopDomain, "one.myshopify.com"); assert.equal(s.centralBodies[0].shopId, "gid://shopify/Shop/1"); assert.equal(s.centralBodies[0].amount, "50.19"); assert.equal(s.centralBodies[0].gateway, "bogus"); });
test("forged query string and body shop identities cannot select the tenant", async () => { const s = setup(); await handleAdministrativeBillingReconciliation(request({ ...target, shop: "forged.myshopify.com", shopId: "gid://shopify/Shop/999" }, "https://app.test/app/billing-reconciliation?shop=forged.myshopify.com"), s.dependencies); assert.equal(s.centralBodies[0].shopDomain, "one.myshopify.com"); assert.equal(s.centralBodies[0].shopId, "gid://shopify/Shop/1"); });
test("cross-linked contract order or cycle is rejected without Central write", async () => { for (const field of ["subscriptionContractId", "shopifyOrderId", "cycleOriginTime"] as const) { const s = setup(); (s.data.subscriptionBillingAttempt as any)[field === "subscriptionContractId" ? "subscriptionContract" : field === "shopifyOrderId" ? "state" : "originTime"] = field === "subscriptionContractId" ? { id: "gid://shopify/SubscriptionContract/11" } : field === "shopifyOrderId" ? { ...s.data.subscriptionBillingAttempt.state, order: { ...s.data.subscriptionBillingAttempt.state.order, id: "gid://shopify/Order/31" } } : "2026-10-27T16:00:00Z"; const response = await handleAdministrativeBillingReconciliation(request(), s.dependencies); assert.equal(response.status, 409); assert.equal(s.centralBodies.length, 0); } });
test("non-test order and non-bogus gateway fail closed", async () => { for (const mutate of [(s: any) => { s.data.subscriptionBillingAttempt.state.order.test = false; }, (s: any) => { s.data.subscriptionBillingAttempt.state.order.transactions[0].gateway = "other"; }]) { const s = setup(); mutate(s); const response = await handleAdministrativeBillingReconciliation(request(), s.dependencies); assert.equal(response.status, 409); assert.equal(s.centralBodies.length, 0); } });
test("query is statically read-only and has no financial mutation surface", () => { assert.match(ADMINISTRATIVE_RECONCILIATION_QUERY, /^#graphql\s*query/); for (const forbidden of ["subscriptionBillingAttemptCreate", "orderCreate", "mutation", "stripe", "email", "webhook"] ) assert.equal(ADMINISTRATIVE_RECONCILIATION_QUERY.toLowerCase().includes(forbidden.toLowerCase()), false); });
test("tokens and server secrets never appear in payload logs or response", async () => { const s = setup(); const response = await handleAdministrativeBillingReconciliation(request(), s.dependencies); const serialized = JSON.stringify({ body: s.centralBodies, logs: s.logs, response: await response.json() }); assert.equal(serialized.includes("never-forward"), false); assert.equal(serialized.includes("central-secret"), false); });
