import assert from "node:assert/strict"; import test from "node:test"; import { handleRetryOperation } from "./retry-operation.server";
const base = { shop: "one.myshopify.com", contractId: "gid://shopify/SubscriptionContract/1", operation: "inventory", idempotencyKey: "aps:cycle:inventory:0", lines: [{ variantId: "gid://shopify/ProductVariant/1", quantity: 2 }] };
function request(body = base) { return new Request("https://app.test/api/shopify/retry-operation", { method: "POST", headers: { "content-type": "application/json", "x-api-key": "secret", "idempotency-key": body.idempotencyKey }, body: JSON.stringify(body) }); }
function deps(nodes: any[]) { return { apiKey: "secret", getAdmin: async () => ({ session: { shop: base.shop }, admin: { graphql: async () => Response.json({ data: { nodes } }) } }) }; }
test("internal endpoint without x-api-key returns 401", async () => { const response = await handleRetryOperation(new Request("https://app.test/api/shopify/retry-operation", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": base.idempotencyKey }, body: JSON.stringify(base) }), deps([])); assert.equal(response.status, 401); assert.equal((await response.json() as any).errorCode, "unauthorized"); });
test("expired Shopify authentication returns explicit reauthorization and performs no GraphQL", async () => { let calls = 0; const response = await handleRetryOperation(request(), { apiKey: "secret", getAdmin: async () => { calls++; throw new Response("unauthorized", { status: 401 }); } }); const payload = await response.json() as any; assert.equal(response.status, 401); assert.equal(payload.errorCode, "shopify_reauthentication_required"); assert.equal(payload.uncertain, false); assert.equal(calls, 1); });
test("offline session infrastructure failure is retryable and does not masquerade as OAuth", async () => { const response = await handleRetryOperation(request(), { apiKey: "secret", getAdmin: async () => { throw new Error("database unavailable with token secret-value"); } }); const payload = await response.json() as any; assert.equal(response.status, 503); assert.equal(payload.errorCode, "shopify_session_unavailable"); assert.equal(payload.uncertain, true); assert.equal(JSON.stringify(payload).includes("secret-value"), false); });
test("internal endpoint rejects a wrong key and accepts the Central API key without logging it", async () => { const wrong = new Request("https://app.test/api/shopify/retry-operation", { method: "POST", headers: { "content-type": "application/json", "x-api-key": "wrong-secret", "idempotency-key": base.idempotencyKey }, body: JSON.stringify(base) }); assert.equal((await handleRetryOperation(wrong, deps([]))).status, 403); const seen: any[] = []; const response = await handleRetryOperation(request(), { apiKey: "secret", getAdmin: async shop => { seen.push(shop); return deps([{ id: base.lines[0].variantId, inventoryPolicy: "CONTINUE", inventoryItem: { tracked: true } }]).getAdmin(); } }); assert.equal(response.status, 200); assert.deepEqual(seen, [base.shop]); assert.equal(JSON.stringify(seen).includes("secret"), false); });
test("exact inventory is sufficient", async () => { const response = await handleRetryOperation(request(), deps([{ id: base.lines[0].variantId, inventoryPolicy: "DENY", inventoryItem: { tracked: true, inventoryLevels: { nodes: [{ quantities: [{ name: "available", quantity: 2 }] }] } } }])); assert.equal((await response.json() as any).available, true); });
test("removed variant blocks", async () => assert.equal((await (await handleRetryOperation(request(), deps([]))).json() as any).available, false));
test("one insufficient line blocks a multi-line cycle", async () => { const body = { ...base, lines: [...base.lines, { variantId: "gid://shopify/ProductVariant/2", quantity: 3 }] }; const response = await handleRetryOperation(request(body), deps([{ id: base.lines[0].variantId, inventoryPolicy: "DENY", inventoryItem: { tracked: true, inventoryLevels: { nodes: [{ quantities: [{ name: "available", quantity: 2 }] }] } } }, { id: body.lines[1].variantId, inventoryPolicy: "DENY", inventoryItem: { tracked: true, inventoryLevels: { nodes: [{ quantities: [{ name: "available", quantity: 2 }] }] } } }])); assert.equal((await response.json() as any).available, false); });
test("untracked and CONTINUE do not block", async () => { for (const node of [{ id: base.lines[0].variantId, inventoryPolicy: "DENY", inventoryItem: { tracked: false } }, { id: base.lines[0].variantId, inventoryPolicy: "CONTINUE", inventoryItem: { tracked: true } }]) assert.equal((await (await handleRetryOperation(request(), deps([node]))).json() as any).available, true); });
test("GraphQL errors are never reported as available", async () => { const response = await handleRetryOperation(request(), { apiKey: "secret", getAdmin: async () => ({ session: { shop: base.shop }, admin: { graphql: async () => Response.json({ errors: [{ message: "bad" }] }) } }) }); assert.equal(response.status, 502); });
test("aggregates duplicate variant quantities", async () => { const body = { ...base, lines: [{ ...base.lines[0], quantity: 2 }, { ...base.lines[0], quantity: 2 }] }; const response = await handleRetryOperation(request(body), deps([{ id: base.lines[0].variantId, inventoryPolicy: "DENY", inventoryItem: { tracked: true, inventoryLevels: { nodes: [{ quantities: [{ name: "available", quantity: 3 }] }] } } }])); const payload = await response.json() as any; assert.equal(payload.available, false); assert.equal(payload.checks.length, 1); assert.equal(payload.checks[0].required, 4); });
test("charge requires strict ISO billingCycleAt", async () => { for (const billingCycleAt of ["2026-08-20", "not-a-date", "2026-99-99T00:00:00Z"]) { const body = { ...base, operation: "charge", billingCycleAt }; assert.equal((await handleRetryOperation(request(body), deps([]))).status, 400); } });
test("reconciles a pending attempt by id and idempotency key", async () => { const body = { ...base, operation: "reconcile", billingAttemptId: "gid://shopify/SubscriptionBillingAttempt/9" }; const response = await handleRetryOperation(request(body), { apiKey: "secret", getAdmin: async () => ({ session: { shop: base.shop }, admin: { graphql: async () => Response.json({ data: { subscriptionBillingAttempt: { id: body.billingAttemptId, idempotencyKey: body.idempotencyKey, ready: false, order: null } } }) } }) }); const payload = await response.json() as any; assert.equal(payload.status, "pending"); assert.equal(payload.uncertain, true); assert.equal(payload.billingAttemptId, body.billingAttemptId); });
test("timeout uses standard uncertain envelope", async () => { const response = await handleRetryOperation(request(), { apiKey: "secret", timeoutMs: 1, getAdmin: async () => ({ session: { shop: base.shop }, admin: { graphql: async (_q: string, { signal }: any) => new Promise((_resolve, reject) => signal.addEventListener("abort", () => reject(new Error("aborted")))) } }) }); const payload = await response.json() as any; assert.equal(response.status, 504); assert.equal(payload.errorCode, "shopify_timeout"); assert.equal(payload.uncertain, true); assert.equal(payload.success, false); });
test("successful charge returns real external IDs and money", async () => { const body = { ...base, operation: "charge", billingCycleAt: "2026-08-20T12:00:00.000Z" }; const response = await handleRetryOperation(request(body), { apiKey: "secret", getAdmin: async () => ({ session: { shop: base.shop }, admin: { graphql: async () => Response.json({ data: { subscriptionBillingAttemptCreate: { subscriptionBillingAttempt: { id: "gid://shopify/SubscriptionBillingAttempt/1", ready: true, order: { id: "gid://shopify/Order/1", currentTotalPriceSet: { shopMoney: { amount: "20.00", currencyCode: "BRL" } } } }, userErrors: [] } } }) } }) }); const payload = await response.json() as any; assert.equal(payload.success, true); assert.equal(payload.status, "succeeded"); assert.equal(payload.orderId, "gid://shopify/Order/1"); assert.equal(payload.amount, "20.00"); });
test("failed charge returns normalized Shopify error", async () => { const body = { ...base, operation: "charge", billingCycleAt: "2026-08-20T12:00:00Z" }; const response = await handleRetryOperation(request(body), { apiKey: "secret", getAdmin: async () => ({ session: { shop: base.shop }, admin: { graphql: async () => Response.json({ data: { subscriptionBillingAttemptCreate: { subscriptionBillingAttempt: { id: "gid://shopify/SubscriptionBillingAttempt/1", ready: true, errorCode: "CARD_DECLINED", errorMessage: "Declined", order: null }, userErrors: [] } } }) } }) }); const payload = await response.json() as any; assert.equal(payload.success, false); assert.equal(payload.status, "failed"); assert.equal(payload.errorCode, "CARD_DECLINED"); assert.equal(payload.uncertain, false); });
