import assert from "node:assert/strict"; import test from "node:test"; import { handleRetryOperation } from "./retry-operation.server";
const base = { shop: "one.myshopify.com", contractId: "gid://shopify/SubscriptionContract/1", operation: "inventory", idempotencyKey: "aps:cycle:inventory:0", lines: [{ variantId: "gid://shopify/ProductVariant/1", quantity: 2 }] };
function request(body = base) { return new Request("https://app.test/api/shopify/retry-operation", { method: "POST", headers: { "content-type": "application/json", "x-api-key": "secret", "idempotency-key": body.idempotencyKey }, body: JSON.stringify(body) }); }
function deps(nodes: any[]) { return { apiKey: "secret", getAdmin: async () => ({ session: { shop: base.shop }, admin: { graphql: async () => Response.json({ data: { nodes } }) } }) }; }
test("exact inventory is sufficient", async () => { const response = await handleRetryOperation(request(), deps([{ id: base.lines[0].variantId, inventoryPolicy: "DENY", inventoryItem: { tracked: true, inventoryLevels: { nodes: [{ quantities: [{ name: "available", quantity: 2 }] }] } } }])); assert.equal((await response.json() as any).available, true); });
test("removed variant blocks", async () => assert.equal((await (await handleRetryOperation(request(), deps([]))).json() as any).available, false));
test("one insufficient line blocks a multi-line cycle", async () => { const body = { ...base, lines: [...base.lines, { variantId: "gid://shopify/ProductVariant/2", quantity: 3 }] }; const response = await handleRetryOperation(request(body), deps([{ id: base.lines[0].variantId, inventoryPolicy: "DENY", inventoryItem: { tracked: true, inventoryLevels: { nodes: [{ quantities: [{ name: "available", quantity: 2 }] }] } } }, { id: body.lines[1].variantId, inventoryPolicy: "DENY", inventoryItem: { tracked: true, inventoryLevels: { nodes: [{ quantities: [{ name: "available", quantity: 2 }] }] } } }])); assert.equal((await response.json() as any).available, false); });
test("untracked and CONTINUE do not block", async () => { for (const node of [{ id: base.lines[0].variantId, inventoryPolicy: "DENY", inventoryItem: { tracked: false } }, { id: base.lines[0].variantId, inventoryPolicy: "CONTINUE", inventoryItem: { tracked: true } }]) assert.equal((await (await handleRetryOperation(request(), deps([node]))).json() as any).available, true); });
test("GraphQL errors are never reported as available", async () => { const response = await handleRetryOperation(request(), { apiKey: "secret", getAdmin: async () => ({ session: { shop: base.shop }, admin: { graphql: async () => Response.json({ errors: [{ message: "bad" }] }) } }) }); assert.equal(response.status, 502); });
