import { useEffect } from "react";
import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { Form, useActionData, useLoaderData, useNavigation } from "react-router";
import { useAppBridge } from "@shopify/app-bridge-react";
import { loadRetrySettingsWithMigration, retrySettingsRequest } from "../lib/retry-settings-api.server";
import { authenticate } from "../shopify.server";
import prisma from "../db.server";

const ACTIONS = new Set(["PAUSE_AND_NOTIFY", "CANCEL_AND_NOTIFY", "SKIP_AND_NOTIFY"]);
const FREQUENCIES = new Set(["IMMEDIATELY", "DAILY_SUMMARY", "WEEKLY_SUMMARY", "NEVER"]);
function boundedInteger(formData: FormData, name: string, min: number, max: number) { const value = Number(formData.get(name)); return Number.isInteger(value) && value >= min && value <= max ? value : null; }
export const loader = async ({ request }: LoaderFunctionArgs) => { const { session } = await authenticate.admin(request); const settings = await loadRetrySettingsWithMigration(session.shop, prisma.billingRetrySettings); const shopHandle = session.shop.replace(/\.myshopify\.com$/i, ""); return { settings, notificationsUrl: `https://admin.shopify.com/store/${shopHandle}/settings/notifications/customer` }; };
export const action = async ({ request }: ActionFunctionArgs) => {
  const { session } = await authenticate.admin(request); const formData = await request.formData();
  const paymentRetryAttempts = boundedInteger(formData, "paymentRetryAttempts", 0, 10), paymentRetryDays = boundedInteger(formData, "paymentRetryDays", 1, 14), inventoryRetryAttempts = boundedInteger(formData, "inventoryRetryAttempts", 0, 10), inventoryRetryDays = boundedInteger(formData, "inventoryRetryDays", 1, 14);
  const paymentFailureAction = String(formData.get("paymentFailureAction") || ""), inventoryFailureAction = String(formData.get("inventoryFailureAction") || ""), teamNotificationFrequency = String(formData.get("teamNotificationFrequency") || "");
  if ([paymentRetryAttempts, paymentRetryDays, inventoryRetryAttempts, inventoryRetryDays].includes(null) || !ACTIONS.has(paymentFailureAction) || !ACTIONS.has(inventoryFailureAction) || !FREQUENCIES.has(teamNotificationFrequency)) return { ok: false, message: "Revise os limites e opções informados." };
  try { const saved = await retrySettingsRequest(session.shop, "PUT", { paymentRetryAttempts: paymentRetryAttempts!, paymentRetryDays: paymentRetryDays!, paymentFailureAction, inventoryRetryAttempts: inventoryRetryAttempts!, inventoryRetryDays: inventoryRetryDays!, inventoryFailureAction, teamNotificationFrequency }); return { ok: true, message: "Configurações salvas.", updatedAt: saved.updatedAt }; } catch { return { ok: false, message: "A API Central não confirmou a gravação. Tente novamente." }; }
};
export default function SettingsPage() {
  const { settings, notificationsUrl } = useLoaderData<typeof loader>(); const actionData = useActionData<typeof action>(); const navigation = useNavigation(); const shopify = useAppBridge(); useEffect(() => { if (actionData?.ok) shopify.toast.show(actionData.message); }, [actionData, shopify]); const updatedAt = actionData?.updatedAt || settings.updatedAt;
  return <s-page heading="Configurações" inlineSize="large">{actionData && !actionData.ok ? <s-banner heading="Não foi possível salvar" tone="critical">{actionData.message}</s-banner> : null}<s-text color="subdued">Última atualização: {updatedAt ? new Date(updatedAt).toLocaleString("pt-BR") : "ainda não salva"}</s-text><Form method="post" data-save-bar data-discard-confirmation><s-grid gridTemplateColumns="280px minmax(0, 1fr)" gap="large">
    <s-box paddingBlockStart="base"><s-stack direction="block" gap="base"><s-heading>Tentativas de faturamento</s-heading><s-paragraph>Controle novas tentativas depois de falhas de pagamento ou estoque.</s-paragraph></s-stack></s-box>
    <s-section heading="Falha na forma de pagamento"><s-stack direction="block" gap="large">
      <s-grid gridTemplateColumns="1fr 1fr" gap="base"><s-stack direction="block" gap="small"><s-number-field label="Número de novas tentativas" name="paymentRetryAttempts" value={String(settings.paymentRetryAttempts)} min={0} max={10} step={1} required /><s-text color="subdued">Mínimo 0, máximo 10</s-text></s-stack><s-stack direction="block" gap="small"><s-number-field label="Dias entre novas tentativas de pagamento" name="paymentRetryDays" value={String(settings.paymentRetryDays)} min={1} max={14} step={1} required /><s-text color="subdued">Mínimo 1, máximo 14 dias</s-text></s-stack></s-grid>
      <s-select label="Ação ao esgotar as tentativas" name="paymentFailureAction" value={settings.paymentFailureAction}><s-option value="PAUSE_AND_NOTIFY">Pausar assinatura e notificar</s-option><s-option value="CANCEL_AND_NOTIFY">Cancelar assinatura e notificar</s-option><s-option value="SKIP_AND_NOTIFY">Pular ciclo e notificar</s-option></s-select><s-divider /><s-heading>Estoque insuficiente</s-heading>
      <s-grid gridTemplateColumns="1fr 1fr" gap="base"><s-stack direction="block" gap="small"><s-number-field label="Número de novas verificações" name="inventoryRetryAttempts" value={String(settings.inventoryRetryAttempts)} min={0} max={10} step={1} required /><s-text color="subdued">Mínimo 0, máximo 10</s-text></s-stack><s-stack direction="block" gap="small"><s-number-field label="Dias entre novas verificações de estoque" name="inventoryRetryDays" value={String(settings.inventoryRetryDays)} min={1} max={14} step={1} required /><s-text color="subdued">Mínimo 1, máximo 14 dias</s-text></s-stack></s-grid>
      <s-select label="Ação ao esgotar as verificações" name="inventoryFailureAction" value={settings.inventoryFailureAction}><s-option value="SKIP_AND_NOTIFY">Pular ciclo e notificar</s-option><s-option value="PAUSE_AND_NOTIFY">Pausar assinatura e notificar</s-option><s-option value="CANCEL_AND_NOTIFY">Cancelar assinatura e notificar</s-option></s-select>
      <s-select label="Frequência de notificações para a equipe" name="teamNotificationFrequency" value={settings.teamNotificationFrequency}><s-option value="IMMEDIATELY">Imediatamente</s-option><s-option value="DAILY_SUMMARY">Resumo diário</s-option><s-option value="WEEKLY_SUMMARY">Resumo semanal</s-option><s-option value="NEVER">Nunca</s-option></s-select><s-link href={notificationsUrl} target="_top">Editar notificações</s-link><s-stack direction="inline" justifyContent="end"><s-button type="submit" variant="primary" loading={navigation.state === "submitting"}>Salvar</s-button></s-stack>
    </s-stack></s-section>
  </s-grid></Form></s-page>;
}
